### ISSUE TITLE
Actualizar link que está en el icono del logotipo

### ISSUE THREAD

**Issue by leslyMH** [elemprendedoronline/mpatica#25]
Cuando se presiona sobre el logo de MPATICA en el encabezado, quiero que se diriga al index, actualmente se va hacia otra página y no le encuentro la línea de código para modificarle.
Su ayuda con eso.
Gracias.

**Comment by cristyanc** [comment]
Problema resuelto!

**Comment by leslyMH** [comment]
Le comento que cuando hago clic sobre el logo me da error.
